name: Deploy Node.js Lambda Functions

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'  # specify your Node.js version

    - name: Install AWS CLI
      run: |
        pip install awscli

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ca-central-1

    - name: Deploy CreateCalendarEventFunction
      run: |
        cd CreateCalendarEventFunction
        npm install
        zip -r function.zip .
        aws lambda update-function-code --function-name CreateCalendarEventFunction --zip-file fileb://function.zip

    - name: Deploy DeleteCalendarEventFunction
      run: |
        cd DeleteCalendarEventFunction
        npm install
        zip -r function.zip .
        aws lambda update-function-code --function-name DeleteCalendarEventFunction --zip-file fileb://function.zip

    - name: Deploy GetCalendarEventFunction
      run: |
        cd GetCalendarEventFunction
        npm install
        zip -r function.zip .
        aws lambda update-function-code --function-name GetCalendarEventFunction --zip-file fileb://function.zip

    - name: Deploy GetUpcomingEventsFunction
      run: |
        cd GetUpcomingEventsFunction
        npm install
        zip -r function.zip .
        aws lambda update-function-code --function-name GetUpcomingEventsFunction --zip-file fileb://function.zip

    - name: Deploy ListCalendarEventsFunction
      run: |
        cd ListCalendarEventsFunction
        npm install
        zip -r function.zip .
        aws lambda update-function-code --function-name ListCalendarEventsFunction --zip-file fileb://function.zip

    - name: Deploy SearchCalendarEventsFunction
      run: |
        cd SearchCalendarEventsFunction
        npm install
        zip -r function.zip .
        aws lambda update-function-code --function-name SearchCalendarEventsFunction --zip-file fileb://function.zip

    - name: Deploy UpdateCalendarEventFunction
      run: |
        cd UpdateCalendarEventFunction
        npm install
        zip -r function.zip .
        aws lambda update-function-code --function-name UpdateCalendarEventFunction --zip-file fileb://function.zip
        